/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass CheckIfLaunchingMissileData
 *
 */

#ifndef _TEMPLATEMODEL_CHECKIFLAUNCHINGMISSILEDATA_UTILS_H_
#define _TEMPLATEMODEL_CHECKIFLAUNCHINGMISSILEDATA_UTILS_H_

#include "TemplateModel/CheckIfLaunchingMissileData.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */
#define sendFireCmd_fire(data) fireConjPort_fire(&self->constData->sendFireCmd, data)

/* data receive ports */

/* data send ports */

/* saps */
#define timer_startTimer(data) PTimerConjPort_startTimer(&self->constData->timer, data)
#define timer_startTimeout(data) PTimerConjPort_startTimeout(&self->constData->timer, data)
#define timer_kill() PTimerConjPort_kill(&self->constData->timer)
#define timer__startTimer(data) PTimerConjPort__startTimer(&self->constData->timer, data)
#define timer__startTimeout(data) PTimerConjPort__startTimeout(&self->constData->timer, data)

/* replicated event ports */

/* services */

/* operations */

/* attributes */
#define N (self->N)
#define sequenceOfCriticals (self->sequenceOfCriticals)

/* port operations */

#endif /* _TEMPLATEMODEL_CHECKIFLAUNCHINGMISSILEDATA_UTILS_H_ */

