/**
 * @author generated by eTrice
 *
 * Source File of ActorClass CheckIfLaunchingMissileData
 *
 */

#include "CheckIfLaunchingMissileData.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"
#ifdef ET_MSC_TRACER_ACTIVATE
	#include "debugging/etMSCTracer.h"
#endif

#include "TemplateModel/fire.h"
#include "TemplateModel/uwbInfo.h"
#include "etrice/api/timer/PTimer.h"

#include "CheckIfLaunchingMissileData_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_sendFireCmd = 1,
	IFITEM_receiveDistance = 2,
	IFITEM_timer = 3
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_checking = 2,
	STATE_checkingAgain = 3,
	STATE_afterTimeout = 4,
	STATE_MAX = 5
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__checking = 1,
	CHAIN_TRANS_dist_received_FROM_checking_TO_cp0_BY_valuereceiveDistance = 2,
	CHAIN_TRANS_tr2_FROM_afterTimeout_TO_checking_BY_valuereceiveDistance = 3,
	CHAIN_TRANS_tr3_FROM_checkingAgain_TO_afterTimeout_BY_timeouttimer = 4
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_receiveDistance__value = IFITEM_receiveDistance + EVT_SHIFT*uwbInfo_IN_value,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout,
	TRIG_timer___timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT__timeout
};

/* state names */
#ifdef ET_MSC_LOGGER_ACTIVATE
	static const char* stateStrings[] = {"<no state>","<top>","checking",
	"checkingAgain",
	"afterTimeout"
	};
#endif

static void setState(CheckIfLaunchingMissileData* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state]);
}

static etInt16 getState(CheckIfLaunchingMissileData* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_dist_received_FROM_checking_TO_cp0_BY_valuereceiveDistance(CheckIfLaunchingMissileData* self, const InterfaceItemBase* ifitem, float32 transitionData) {
	if (transitionData < 5.0)
	{
	    if (sequenceOfCriticals == 0)
	    {
	        // proracunavanje na osnovu distance
	        float32 missileParams = transitionData * 2;
	        printf("10 uzastopnih detekcija nadolazeceg projektila!\n");
	      
	        sendFireCmd_fire(missileParams);
	        sequenceOfCriticals--;
	    }
	    else
	    {
	        sequenceOfCriticals--;
	    }
	}
	else
	{
	    sequenceOfCriticals = 10;
	}
}
static void action_TRANS_tr2_FROM_afterTimeout_TO_checking_BY_valuereceiveDistance(CheckIfLaunchingMissileData* self, const InterfaceItemBase* ifitem, float32 transitionData) {
	if (transitionData < 5.0)
	{
	    printf("ALARM!!!!\n\n");
	}
}
static void action_TRANS_tr1_FROM_cp0_TO_checkingAgain_COND_tr1(CheckIfLaunchingMissileData* self, const InterfaceItemBase* ifitem, float32 transitionData) {
	timer_startTimeout(500);
	sequenceOfCriticals = 10;
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(CheckIfLaunchingMissileData* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_afterTimeout:
				self->history[STATE_TOP] = STATE_afterTimeout;
				current__et = STATE_TOP;
				break;
			case STATE_checking:
				self->history[STATE_TOP] = STATE_checking;
				current__et = STATE_TOP;
				break;
			case STATE_checkingAgain:
				self->history[STATE_TOP] = STATE_checkingAgain;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(CheckIfLaunchingMissileData* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__checking:
		{
			return STATE_checking;
		}
		case CHAIN_TRANS_dist_received_FROM_checking_TO_cp0_BY_valuereceiveDistance:
		{
			float32 transitionData = *((float32*) generic_data__et);
			ET_TOUCH(transitionData);
			action_TRANS_dist_received_FROM_checking_TO_cp0_BY_valuereceiveDistance(self, ifitem, transitionData);
			if (sequenceOfCriticals==-1) {
			action_TRANS_tr1_FROM_cp0_TO_checkingAgain_COND_tr1(self, ifitem, transitionData);
			return STATE_checkingAgain;}
			else {
			return STATE_checking;}
		}
		case CHAIN_TRANS_tr2_FROM_afterTimeout_TO_checking_BY_valuereceiveDistance:
		{
			float32 transitionData = *((float32*) generic_data__et);
			ET_TOUCH(transitionData);
			action_TRANS_tr2_FROM_afterTimeout_TO_checking_BY_valuereceiveDistance(self, ifitem, transitionData);
			return STATE_checking;
		}
		case CHAIN_TRANS_tr3_FROM_checkingAgain_TO_afterTimeout_BY_timeouttimer:
		{
			return STATE_afterTimeout;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(CheckIfLaunchingMissileData* self, etInt16 state__et) {
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_afterTimeout:
				/* in leaf state: return state id */
				return STATE_afterTimeout;
			case STATE_checking:
				/* in leaf state: return state id */
				return STATE_checking;
			case STATE_checkingAgain:
				/* in leaf state: return state id */
				return STATE_checkingAgain;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void CheckIfLaunchingMissileData_executeInitTransition(CheckIfLaunchingMissileData* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__checking;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void CheckIfLaunchingMissileData_receiveEventInternal(CheckIfLaunchingMissileData* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_afterTimeout:
				switch(trigger__et) {
					case TRIG_receiveDistance__value:
						{
							chain__et = CHAIN_TRANS_tr2_FROM_afterTimeout_TO_checking_BY_valuereceiveDistance;
							catching_state__et = STATE_TOP;
						}
					break;
					default:
						/* should not occur */
						break;
				}
				break;
			case STATE_checking:
				switch(trigger__et) {
					case TRIG_receiveDistance__value:
						{
							chain__et = CHAIN_TRANS_dist_received_FROM_checking_TO_cp0_BY_valuereceiveDistance;
							catching_state__et = STATE_TOP;
						}
					break;
					default:
						/* should not occur */
						break;
				}
				break;
			case STATE_checkingAgain:
				switch(trigger__et) {
					case TRIG_timer__timeout:
						{
							chain__et = CHAIN_TRANS_tr3_FROM_checkingAgain_TO_afterTimeout_BY_timeouttimer;
							catching_state__et = STATE_TOP;
						}
					break;
					default:
						/* should not occur */
						break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void CheckIfLaunchingMissileData_receiveEvent(CheckIfLaunchingMissileData* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	CheckIfLaunchingMissileData_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void CheckIfLaunchingMissileData_init(CheckIfLaunchingMissileData* self){
	ET_MSC_LOGGER_SYNC_ENTRY("CheckIfLaunchingMissileData", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<CHECKIFLAUNCHINGMISSILEDATA_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	CheckIfLaunchingMissileData_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void CheckIfLaunchingMissileData_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("CheckIfLaunchingMissileData", "_receiveMessage")
	CheckIfLaunchingMissileData_receiveEvent((CheckIfLaunchingMissileData*) self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

