/**
 * @author generated by eTrice
 *
 * Header File of ActorClass CheckIfLaunchingMissileData
 *
 */

#ifndef _TEMPLATEMODEL_CHECKIFLAUNCHINGMISSILEDATA_H_
#define _TEMPLATEMODEL_CHECKIFLAUNCHINGMISSILEDATA_H_

#include "modelbase/etActor.h"

/* include all referenced room classes */
#include "TemplateModel/fire.h"
#include "TemplateModel/uwbInfo.h"
#include "etrice/api/timer/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "FreeRTOS.h"
						#include "task.h"
						#include <stdio.h>
						#include "pico/stdlib.h"
						#include <queue.h>
						#include "hardware/adc.h"
						#include "hardware/watchdog.h"
						#include "semphr.h"
						#include "hardware/i2c.h"
						#include "pico/binary_info.h"
						#include "lcd.h"
						
						#include <ctype.h>
						#include "ultrsonic.h"
						#include <string.h>
						

/*--------------------- end user code ---------------------*/

typedef struct CheckIfLaunchingMissileData CheckIfLaunchingMissileData;

/* const part of ActorClass (ROM) */
typedef struct CheckIfLaunchingMissileData_const {
	#ifdef ET_MSC_LOGGER_ACTIVATE
		const char* instName;
	#endif
	
	/* simple ports */
	const fireConjPort sendFireCmd;
	const uwbInfoPort receiveDistance;

	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;

	/* replicated ports */

	/* services */
} CheckIfLaunchingMissileData_const;


/* constant for state machine data */
#define CHECKIFLAUNCHINGMISSILEDATA_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct CheckIfLaunchingMissileData {
	const CheckIfLaunchingMissileData_const* ET_CONST_MEMBER constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int32 N;
	 int32 sequenceOfCriticals;


	/* state machine variables */
	etInt16 state;
	etInt16 history[CHECKIFLAUNCHINGMISSILEDATA_HISTORY_SIZE];
};

void CheckIfLaunchingMissileData_init(CheckIfLaunchingMissileData* self);

void CheckIfLaunchingMissileData_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_CHECKIFLAUNCHINGMISSILEDATA_H_ */

