/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass fire
 * 
 */

#ifndef _TEMPLATEMODEL_FIRE_UTILS_H_
#define _TEMPLATEMODEL_FIRE_UTILS_H_

#include "TemplateModel/fire.h"

/*
 * access macros for operations and attributes
*/


#endif /* _TEMPLATEMODEL_FIRE_UTILS_H_ */

