/**
 * @author generated by eTrice
 *
 * Source File of ActorClass FireMissile
 *
 */

#include "FireMissile.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"
#ifdef ET_MSC_TRACER_ACTIVATE
	#include "debugging/etMSCTracer.h"
#endif

#include "TemplateModel/fire.h"
#include "TemplateModel/sendInfoCriticalFL.h"
#include "etrice/api/timer/PTimer.h"

#include "FireMissile_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_receiveFireCmd = 1,
	IFITEM_receiveCrititcalInfo = 2,
	IFITEM_timer = 3
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_flLevelCritical = 2,
	STATE_flLvlOk = 3,
	STATE_flLevelCritical_InitialState = 4,
	STATE_flLvlOk_launching = 5,
	STATE_MAX = 6
};

/* transition chains */
enum ChainIDs {
	CHAIN_flLevelCritical_TRANS_INITIAL_TO__InitialState = 1,
	CHAIN_flLevelCritical_TRANS_tr0_FROM_InitialState_TO_InitialState_BY_firereceiveFireCmd_tr0 = 2,
	CHAIN_flLvlOk_TRANS_INITIAL_TO__launching = 3,
	CHAIN_flLvlOk_TRANS_receivedMissileParams_FROM_launching_TO_launching_BY_firereceiveFireCmd_receivedMissileParams = 4,
	CHAIN_TRANS_tr0_FROM_flLvlOk_TO_flLevelCritical_BY_criticalNOKreceiveCrititcalInfo = 5,
	CHAIN_TRANS_INITIAL_TO__flLvlOk = 6,
	CHAIN_TRANS_criticakOKagain_FROM_flLevelCritical_TO_flLvlOk_BY_criticalOkreceiveCrititcalInfo = 7
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_receiveFireCmd__fire = IFITEM_receiveFireCmd + EVT_SHIFT*fire_IN_fire,
	TRIG_receiveCrititcalInfo__criticalOk = IFITEM_receiveCrititcalInfo + EVT_SHIFT*sendInfoCriticalFL_IN_criticalOk,
	TRIG_receiveCrititcalInfo__criticalNOK = IFITEM_receiveCrititcalInfo + EVT_SHIFT*sendInfoCriticalFL_IN_criticalNOK,
	TRIG_timer__timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT_timeout,
	TRIG_timer___timeout = IFITEM_timer + EVT_SHIFT*PTimer_OUT__timeout
};

/* state names */
#ifdef ET_MSC_LOGGER_ACTIVATE
	static const char* stateStrings[] = {"<no state>","<top>","flLevelCritical",
	"flLvlOk",
	"flLevelCritical_InitialState",
	"flLvlOk_launching"
	};
#endif

static void setState(FireMissile* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state]);
}

static etInt16 getState(FireMissile* self) {
	return self->state;
}

/* Entry and Exit Codes */
static void entry_flLevelCritical(FireMissile* self) {
	vTaskDelay(pdMS_TO_TICKS(2000));
	printf("Zbog nedovoljnog goriva ne moze se ispaliti projektil.\n");
	       
}

/* Action Codes */
static void action_flLevelCritical_TRANS_tr0_FROM_InitialState_TO_InitialState_BY_firereceiveFireCmd_tr0(FireMissile* self, const InterfaceItemBase* ifitem, float32 transitionData) {
	vTaskDelay(pdMS_TO_TICKS(20));
	printf("Zbog nedovoljnog goriva ne moze se ispaliti projektil.\n");
}
static void action_flLvlOk_TRANS_INITIAL_TO__launching(FireMissile* self) {
	criticalReportedWl=false;
}
static void action_flLvlOk_TRANS_receivedMissileParams_FROM_launching_TO_launching_BY_firereceiveFireCmd_receivedMissileParams(FireMissile* self, const InterfaceItemBase* ifitem, float32 transitionData) {
	for (int i = 3; i > 0; i--)
	       {
	          printf("ISPALJUJE SE PROJEKTIL!!! ... %d\n", i);
	                  vTaskDelay( pdMS_TO_TICKS(800)); 
	              }
	          
	       
	
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(FireMissile* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_flLevelCritical:
				self->history[STATE_TOP] = STATE_flLevelCritical;
				current__et = STATE_TOP;
				break;
			case STATE_flLevelCritical_InitialState:
				self->history[STATE_flLevelCritical] = STATE_flLevelCritical_InitialState;
				current__et = STATE_flLevelCritical;
				break;
			case STATE_flLvlOk:
				self->history[STATE_TOP] = STATE_flLvlOk;
				current__et = STATE_TOP;
				break;
			case STATE_flLvlOk_launching:
				self->history[STATE_flLvlOk] = STATE_flLvlOk_launching;
				current__et = STATE_flLvlOk;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(FireMissile* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__flLvlOk:
		{
			return STATE_flLvlOk;
		}
		case CHAIN_TRANS_criticakOKagain_FROM_flLevelCritical_TO_flLvlOk_BY_criticalOkreceiveCrititcalInfo:
		{
			return STATE_flLvlOk;
		}
		case CHAIN_TRANS_tr0_FROM_flLvlOk_TO_flLevelCritical_BY_criticalNOKreceiveCrititcalInfo:
		{
			return STATE_flLevelCritical;
		}
		case CHAIN_flLevelCritical_TRANS_INITIAL_TO__InitialState:
		{
			return STATE_flLevelCritical_InitialState;
		}
		case CHAIN_flLevelCritical_TRANS_tr0_FROM_InitialState_TO_InitialState_BY_firereceiveFireCmd_tr0:
		{
			float32 transitionData = *((float32*) generic_data__et);
			ET_TOUCH(transitionData);
			action_flLevelCritical_TRANS_tr0_FROM_InitialState_TO_InitialState_BY_firereceiveFireCmd_tr0(self, ifitem, transitionData);
			return STATE_flLevelCritical_InitialState;
		}
		case CHAIN_flLvlOk_TRANS_INITIAL_TO__launching:
		{
			action_flLvlOk_TRANS_INITIAL_TO__launching(self);
			return STATE_flLvlOk_launching;
		}
		case CHAIN_flLvlOk_TRANS_receivedMissileParams_FROM_launching_TO_launching_BY_firereceiveFireCmd_receivedMissileParams:
		{
			float32 transitionData = *((float32*) generic_data__et);
			ET_TOUCH(transitionData);
			action_flLvlOk_TRANS_receivedMissileParams_FROM_launching_TO_launching_BY_firereceiveFireCmd_receivedMissileParams(self, ifitem, transitionData);
			return STATE_flLvlOk_launching;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(FireMissile* self, etInt16 state__et) {
	etBool skip_entry__et = ET_FALSE;
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
		skip_entry__et = ET_TRUE;
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_flLevelCritical:
				if (!(skip_entry__et)) entry_flLevelCritical(self);
				/* state has a sub graph */
				/* with init transition */
				if (self->history[STATE_flLevelCritical]==NO_STATE) {
					state__et = executeTransitionChain(self, CHAIN_flLevelCritical_TRANS_INITIAL_TO__InitialState, NULL, NULL);
				}
				else {
					state__et = self->history[STATE_flLevelCritical];
				}
				break;
			case STATE_flLevelCritical_InitialState:
				/* in leaf state: return state id */
				return STATE_flLevelCritical_InitialState;
			case STATE_flLvlOk:
				/* state has a sub graph */
				/* with init transition */
				if (self->history[STATE_flLvlOk]==NO_STATE) {
					state__et = executeTransitionChain(self, CHAIN_flLvlOk_TRANS_INITIAL_TO__launching, NULL, NULL);
				}
				else {
					state__et = self->history[STATE_flLvlOk];
				}
				break;
			case STATE_flLvlOk_launching:
				/* in leaf state: return state id */
				return STATE_flLvlOk_launching;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
		skip_entry__et = ET_FALSE;
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void FireMissile_executeInitTransition(FireMissile* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__flLvlOk;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void FireMissile_receiveEventInternal(FireMissile* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_flLevelCritical_InitialState:
				switch(trigger__et) {
					case TRIG_receiveCrititcalInfo__criticalOk:
						{
							chain__et = CHAIN_TRANS_criticakOKagain_FROM_flLevelCritical_TO_flLvlOk_BY_criticalOkreceiveCrititcalInfo;
							catching_state__et = STATE_TOP;
						}
					break;
					case TRIG_receiveFireCmd__fire:
						{
							chain__et = CHAIN_flLevelCritical_TRANS_tr0_FROM_InitialState_TO_InitialState_BY_firereceiveFireCmd_tr0;
							catching_state__et = STATE_flLevelCritical;
						}
					break;
					default:
						/* should not occur */
						break;
				}
				break;
			case STATE_flLvlOk_launching:
				switch(trigger__et) {
					case TRIG_receiveCrititcalInfo__criticalNOK:
						{
							chain__et = CHAIN_TRANS_tr0_FROM_flLvlOk_TO_flLevelCritical_BY_criticalNOKreceiveCrititcalInfo;
							catching_state__et = STATE_TOP;
						}
					break;
					case TRIG_receiveFireCmd__fire:
						{
							chain__et = CHAIN_flLvlOk_TRANS_receivedMissileParams_FROM_launching_TO_launching_BY_firereceiveFireCmd_receivedMissileParams;
							catching_state__et = STATE_flLvlOk;
						}
					break;
					default:
						/* should not occur */
						break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void FireMissile_receiveEvent(FireMissile* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	FireMissile_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void FireMissile_init(FireMissile* self){
	ET_MSC_LOGGER_SYNC_ENTRY("FireMissile", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<FIREMISSILE_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	FireMissile_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void FireMissile_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("FireMissile", "_receiveMessage")
	FireMissile_receiveEvent((FireMissile*) self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

