/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass flLvlInfo
 * 
 */

#include "flLvlInfo.h"
#include "debugging/etMSCLogger.h"
#include "flLvlInfo_Utils.h"


/*--------------------- port methods */
etInt32 flLvlInfoReplPort_getReplication(const flLvlInfoReplPort* self) {
	return ((etReplPort*)self)->size;
}



void flLvlInfoConjPort_value(const flLvlInfoConjPort* self, float32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("flLvlInfoConjPort", "value")
		etPort_sendMessage(self, flLvlInfo_IN_value, sizeof(float32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "value", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void flLvlInfoConjReplPort_value_broadcast(const flLvlInfoConjReplPort* self, float32 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("flLvlInfoConjReplPort", "value")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), flLvlInfo_IN_value, sizeof(float32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "value", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void flLvlInfoConjReplPort_value(const flLvlInfoConjReplPort* self, int idx__et, float32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("flLvlInfoConjReplPort", "value")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), flLvlInfo_IN_value, sizeof(float32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "value", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 flLvlInfoConjReplPort_getReplication(const flLvlInfoConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



/*--------------------- debug helpers */
#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	
	/* message names as strings for debugging (generate MSC) */
	static const char* const flLvlInfo_messageStrings[] = {"MIN", "value", "MAX"};
	
	const char* flLvlInfo_getMessageString(int msg_id) {
		if (msg_id<flLvlInfo_MSG_MIN || msg_id>flLvlInfo_MSG_MAX+1){
			/* id out of range */
			return "Message ID out of range";
		}
		else{
			return flLvlInfo_messageStrings[msg_id];
		}
	}
#endif
