/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass flLvlInfo
 * 
 */

#ifndef _TEMPLATEMODEL_FLLVLINFO_UTILS_H_
#define _TEMPLATEMODEL_FLLVLINFO_UTILS_H_

#include "TemplateModel/flLvlInfo.h"

/*
 * access macros for operations and attributes
*/


#endif /* _TEMPLATEMODEL_FLLVLINFO_UTILS_H_ */

