/**
 * @author generated by eTrice
 *
 * this class contains the main function running Node node with SubSystem subSystemRef
 * it instantiates Node node with SubSystem subSystemRef and starts and ends the lifecycle
 */

#include <string.h>

#include "node_subSystemRef.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"

#include "osal/etPlatformLifecycle.h"

#ifndef ET_MAIN_FUNCTION_NAME
	#define ET_MAIN_FUNCTION_NAME 	main
#endif

/**
 * eTrice main function
 * creates components and starts and stops the lifecycle
 */

int ET_MAIN_FUNCTION_NAME (
#ifdef ET_DO_NOT_USE_ARGC_ARGV
	void
#else
	int argc, char** argv
#endif
) {

#ifdef ET_DO_NOT_USE_ARGC_ARGV
	int argc = 0;
	char** argv = NULL;
#endif		

	etUserEntry(); /* platform specific */
	
	etLogger_logInfo("***   T H E   B E G I N   ***");
	ET_MSC_LOGGER_OPEN("main");
	ET_DATA_LOGGER_OPEN("main");

	/* startup sequence  of lifecycle */
	node_subSystemRef_init(); 		/* lifecycle init */
	node_subSystemRef_start(); 	/* lifecycle start */

	etUserPreRun(); /* platform specific */

	/* run Scheduler */
	int returnCode = node_subSystemRef_run(argc, argv);

	etUserPostRun(); /* platform specific */

	/* shutdown sequence of lifecycle */
	node_subSystemRef_stop(); 		/* lifecycle stop */
	node_subSystemRef_destroy(); 	/* lifecycle destroy */

	ET_MSC_LOGGER_CLOSE
	ET_DATA_LOGGER_CLOSE
	etLogger_logInfo("***   T H E   E N D   ***");

	etUserExit(); /* platform specific */

	return returnCode;
}

