/**
 * @author generated by eTrice
 *
 * Source File of Node node with SubSystem subSystemRef
 *
 */

#include <stdio.h>
#include <string.h>


#include "node_subSystemRef.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "debugging/etDataLogger.h"
#include "messaging/etSystemProtocol.h"
#include "osal/etPlatformLifecycle.h"
#include "osal/etTimer.h"
#include "osal/etSema.h"
#include "runtime/etRuntime.h"
#include "etRuntimeConfig.h"


/* data for Node node with SubSystem subSystemRef */
typedef struct node_subSystemRef {
	char *name;
	volatile int shutdownRequest;
} node_subSystemRef;

static node_subSystemRef node_subSystemRefInst = {"node_subSystemRef", 0};

static void node_subSystemRef_initActorInstances(void);
static void node_subSystemRef_constructActorInstances(void);

static void logDataHeaders();
static void logData();

/* include instances for all classes */
#include "node_subSystemRef_Inst.h"
#include "node_subSystemRef_Disp.h"

static void node_subSystemRef_initMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "initMessageServices")
	{
		etTime interval;

		/* initialization of all message services */
		interval.sec = 0;
		interval.nSec = 100000000;
		etMessageService_init(
			&msgService_DefaultPhysicalThread,
			msgBuffer_DefaultPhysicalThread,
			DEFAULTPHYSICALTHREAD_POOL_SIZE,
			DEFAULTPHYSICALTHREAD_BLOCK_SIZE,
			1024,
			0,
			interval,
			MsgDispatcher_DefaultPhysicalThread_receiveMessage,
			EXECMODE_MIXED);

	}

	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_startMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "startMessageServices")

	etMessageService_start(&msgService_DefaultPhysicalThread);

	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_stopMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "stopMessageServices")

	etMessageService_stop(&msgService_DefaultPhysicalThread);

	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_destroyMessageServices(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "destroyMessageServices")

	etMessageService_destroy(&msgService_DefaultPhysicalThread);

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_init(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "init")
	etLogger_logInfoF("%s_init", node_subSystemRefInst.name);

	/* construct all actors */
	node_subSystemRef_constructActorInstances();

	/* initialization of all message services */
	node_subSystemRef_initMessageServices();

	/* init all actors */
	node_subSystemRef_initActorInstances();

	/* init data logging */
	logDataHeaders();
	logData();

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_start(void) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "start")
	etLogger_logInfoF("%s_start", node_subSystemRefInst.name);
	node_subSystemRef_startMessageServices();
	ET_MSC_LOGGER_SYNC_EXIT
}

#ifdef ET_RUNNER_ACTIVATE
	// kept for backwards compatibility, moved to life cycle etUserMainRun
	static void generatedMainRun(int argc, char** argv) {
		etBool runAsTest = false;
		if (argc>1 && strcmp(argv[1], "-headless")==0) {
			runAsTest = ET_TRUE;
		} if (argc>1 && strcmp(argv[1], "-run_as_test")==0) {
			runAsTest = ET_TRUE;	
		}
	
		if (runAsTest) {
			etSema_waitForWakeup(etRuntime_getTerminateSemaphore());
		}
		else {
			printf("type quit to exit\n");
			fflush(stdout);
			while (ET_TRUE) {
				char line[64];
	
				if (fgets(line, 64, stdin) != NULL) {
					if (strncmp(line, "quit", 4)==0)
						break;
				}
			}
		}
	}
#endif

int node_subSystemRef_run(int argc, char** argv) {
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "run")
	
	#ifndef ET_USER_MAIN_RUN
		// deprecated
		#ifdef ET_RUNNER_ACTIVATE
			generatedMainRun(argc, argv);
		#endif
		return 0;
	#else
		return etUserMainRun(argc, argv);
	#endif

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_stop(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "stop")
	etLogger_logInfoF("%s_stop", node_subSystemRefInst.name);

	node_subSystemRef_stopMessageServices();

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_destroy(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "destroy")
	etLogger_logInfoF("%s_destroy", node_subSystemRefInst.name);


	node_subSystemRef_destroyMessageServices();

	ET_MSC_LOGGER_SYNC_EXIT
}

void node_subSystemRef_shutdown(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "shutdown")
	etLogger_logInfoF("%s_shutdown", node_subSystemRefInst.name);

	node_subSystemRefInst.shutdownRequest = 1;

	ET_MSC_LOGGER_SYNC_EXIT
}


static void node_subSystemRef_constructActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "constructActorInstances")


	ET_MSC_LOGGER_SYNC_EXIT
}

static void node_subSystemRef_initActorInstances(void){
	ET_MSC_LOGGER_SYNC_ENTRY("node_subSystemRef", "initActorInstances")

	TopActor_init(&_LogSys_subSystemRef_topActor);
	TempActor_init(&_LogSys_subSystemRef_topActor_tempSensor);
	WaterLevelActor_init(&_LogSys_subSystemRef_topActor_fuelLvlSensor);
	NotifyOperatorWLCmd_init(&_LogSys_subSystemRef_topActor_fuelLevelControler);
	UwbSensorMissileData_init(&_LogSys_subSystemRef_topActor_missilePositionReceiver);
	NotifyOperatorTempCmd_init(&_LogSys_subSystemRef_topActor_tempLevelController);
	FireMissile_init(&_LogSys_subSystemRef_topActor_fireMissile);
	CheckIfLaunchingMissileData_init(&_LogSys_subSystemRef_topActor_calculateIfLaunching);
	ATimerService_init(&_LogSys_subSystemRef_timingService);

	ET_MSC_LOGGER_SYNC_EXIT
}

static void logDataHeaders() {
}

static void logData() {
	ET_DATA_LOGGER_NEW_ROW
}
