/**
 * @author generated by eTrice
 *
 * Header File of ActorClass NotifyOperatorWLCmd
 *
 */

#ifndef _TEMPLATEMODEL_NOTIFYOPERATORWLCMD_H_
#define _TEMPLATEMODEL_NOTIFYOPERATORWLCMD_H_

#include "modelbase/etActor.h"

/* include all referenced room classes */
#include "TemplateModel/flLvlInfo.h"
#include "TemplateModel/sendInfoCriticalFL.h"

/*--------------------- begin user code ---------------------*/
#include "FreeRTOS.h"
						#include "task.h"
						#include <stdio.h>
						#include "pico/stdlib.h"
						#include <queue.h>
						#include "hardware/adc.h"
						#include "hardware/watchdog.h"
						#include "semphr.h"
						#include "hardware/i2c.h"
						#include "pico/binary_info.h"
						#include "lcd.h"
						
						#include <ctype.h>
						#include "ultrsonic.h"
						#include <string.h>
						


/*--------------------- end user code ---------------------*/

typedef struct NotifyOperatorWLCmd NotifyOperatorWLCmd;

/* const part of ActorClass (ROM) */
typedef struct NotifyOperatorWLCmd_const {
	#ifdef ET_MSC_LOGGER_ACTIVATE
		const char* instName;
	#endif
	
	/* simple ports */
	const flLvlInfoPort receiveWLLevel;
	const sendInfoCriticalFLConjPort sendCritical;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} NotifyOperatorWLCmd_const;


/* constant for state machine data */
#define NOTIFYOPERATORWLCMD_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct NotifyOperatorWLCmd {
	const NotifyOperatorWLCmd_const* ET_CONST_MEMBER constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int32 criticalCount;
	 int32 threshold;
	 float32 wltreshold;
	 bool okreported;
	 bool criticalReportedWl;


	/* state machine variables */
	etInt16 state;
	etInt16 history[NOTIFYOPERATORWLCMD_HISTORY_SIZE];
};

void NotifyOperatorWLCmd_init(NotifyOperatorWLCmd* self);

void NotifyOperatorWLCmd_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_NOTIFYOPERATORWLCMD_H_ */

