/**
 * @author generated by eTrice
 *
 * Source File of ActorClass NotifyOperatorTempCmd
 *
 */

#include "NotifyOperatorTempCmd.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"
#ifdef ET_MSC_TRACER_ACTIVATE
	#include "debugging/etMSCTracer.h"
#endif

#include "TemplateModel/tempLvlInfo.h"

#include "NotifyOperatorTempCmd_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_receiveTempLevel = 1
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_tempLevelNotifying = 2,
	STATE_MAX = 3
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__tempLevelNotifying = 1,
	CHAIN_TRANS_tempLevelReceived_FROM_tempLevelNotifying_TO_tempLevelNotifying_BY_valuereceiveTempLevel_tempLevelReceived = 2
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_receiveTempLevel__value = IFITEM_receiveTempLevel + EVT_SHIFT*tempLvlInfo_IN_value
};

/* state names */
#ifdef ET_MSC_LOGGER_ACTIVATE
	static const char* stateStrings[] = {"<no state>","<top>","tempLevelNotifying"
	};
#endif

static void setState(NotifyOperatorTempCmd* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state]);
}

static etInt16 getState(NotifyOperatorTempCmd* self) {
	return self->state;
}

/* Entry and Exit Codes */

/* Action Codes */
static void action_TRANS_INITIAL_TO__tempLevelNotifying(NotifyOperatorTempCmd* self) {
		criticalCnt = 0;
		threshold = 5;
		LED_PIN = PICO_DEFAULT_LED_PIN;
		tempTreshold = 25.0;
		okreported = false;
		criticalReportedTmp=false;
	gpio_init(LED_PIN);
	gpio_set_dir(LED_PIN, GPIO_OUT);
}
static void action_TRANS_tempLevelReceived_FROM_tempLevelNotifying_TO_tempLevelNotifying_BY_valuereceiveTempLevel_tempLevelReceived(NotifyOperatorTempCmd* self, const InterfaceItemBase* ifitem, int32 transitionData) {
	if (transitionData > tempTreshold)
	       {
	           criticalCnt++;
	           if (criticalCnt >= threshold && !criticalReportedTmp)
	           {
	               gpio_put(LED_PIN, 1);
	
	               lcd_print(1, "CR: temp low");
	               printf("CRITICAL: Temperatura je veca od %f: %f\n", tempTreshold, transitionData);
	               criticalReportedTmp = true;
	           }
	       }
	       else
	       {
	           if (criticalReportedTmp)
	           {
	               gpio_put(LED_PIN, 0);
	               lcd_print(1, "Inf: temp ok");
	               printf("INFO: Temperatura se stabilizovala %f\n", transitionData);
	               criticalReportedTmp = false;
	           }
	           else
	           {
	               if (!okreported)
	               {
	                   lcd_print(1, "Inf: temp ok");
	                   printf("INFO: Nivo temperature je stabilan %f\n", transitionData);
	                   okreported = true;
	               }
	           }
	           criticalCnt = 0;
	       }
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(NotifyOperatorTempCmd* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_tempLevelNotifying:
				self->history[STATE_TOP] = STATE_tempLevelNotifying;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(NotifyOperatorTempCmd* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__tempLevelNotifying:
		{
			action_TRANS_INITIAL_TO__tempLevelNotifying(self);
			return STATE_tempLevelNotifying;
		}
		case CHAIN_TRANS_tempLevelReceived_FROM_tempLevelNotifying_TO_tempLevelNotifying_BY_valuereceiveTempLevel_tempLevelReceived:
		{
			int32 transitionData = *((int32*) generic_data__et);
			ET_TOUCH(transitionData);
			action_TRANS_tempLevelReceived_FROM_tempLevelNotifying_TO_tempLevelNotifying_BY_valuereceiveTempLevel_tempLevelReceived(self, ifitem, transitionData);
			return STATE_tempLevelNotifying;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(NotifyOperatorTempCmd* self, etInt16 state__et) {
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_tempLevelNotifying:
				/* in leaf state: return state id */
				return STATE_tempLevelNotifying;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void NotifyOperatorTempCmd_executeInitTransition(NotifyOperatorTempCmd* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__tempLevelNotifying;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void NotifyOperatorTempCmd_receiveEventInternal(NotifyOperatorTempCmd* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_tempLevelNotifying:
				switch(trigger__et) {
					case TRIG_receiveTempLevel__value:
						{
							chain__et = CHAIN_TRANS_tempLevelReceived_FROM_tempLevelNotifying_TO_tempLevelNotifying_BY_valuereceiveTempLevel_tempLevelReceived;
							catching_state__et = STATE_TOP;
						}
					break;
					default:
						/* should not occur */
						break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void NotifyOperatorTempCmd_receiveEvent(NotifyOperatorTempCmd* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	NotifyOperatorTempCmd_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void NotifyOperatorTempCmd_init(NotifyOperatorTempCmd* self){
	ET_MSC_LOGGER_SYNC_ENTRY("NotifyOperatorTempCmd", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<NOTIFYOPERATORTEMPCMD_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	NotifyOperatorTempCmd_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void NotifyOperatorTempCmd_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("NotifyOperatorTempCmd", "_receiveMessage")
	NotifyOperatorTempCmd_receiveEvent((NotifyOperatorTempCmd*) self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

