/**
 * @author generated by eTrice
 *
 * Utils File of ActorClass NotifyOperatorTempCmd
 *
 */

#ifndef _TEMPLATEMODEL_NOTIFYOPERATORTEMPCMD_UTILS_H_
#define _TEMPLATEMODEL_NOTIFYOPERATORTEMPCMD_UTILS_H_

#include "TemplateModel/NotifyOperatorTempCmd.h"

/*
 * access macros for ports, operations and attributes
*/

/* simple event ports */

/* data receive ports */

/* data send ports */

/* saps */

/* replicated event ports */

/* services */

/* operations */

/* attributes */
#define criticalCnt (self->criticalCnt)
#define threshold (self->threshold)
#define LED_PIN (self->LED_PIN)
#define tempTreshold (self->tempTreshold)
#define okreported (self->okreported)
#define criticalReportedTmp (self->criticalReportedTmp)

/* port operations */

#endif /* _TEMPLATEMODEL_NOTIFYOPERATORTEMPCMD_UTILS_H_ */

