/**
 * @author generated by eTrice
 *
 * Header File of ActorClass NotifyOperatorTempCmd
 *
 */

#ifndef _TEMPLATEMODEL_NOTIFYOPERATORTEMPCMD_H_
#define _TEMPLATEMODEL_NOTIFYOPERATORTEMPCMD_H_

#include "modelbase/etActor.h"

/* include all referenced room classes */
#include "TemplateModel/tempLvlInfo.h"

/*--------------------- begin user code ---------------------*/
#include "FreeRTOS.h"
						#include "task.h"
						#include <stdio.h>
						#include "pico/stdlib.h"
						#include <queue.h>
						#include "hardware/adc.h"
						#include "hardware/watchdog.h"
						#include "semphr.h"
						#include "hardware/i2c.h"
						#include "pico/binary_info.h"
						#include "lcd.h"
						
						#include <ctype.h>
						#include "ultrsonic.h"
						#include <string.h>
						
			


/*--------------------- end user code ---------------------*/

typedef struct NotifyOperatorTempCmd NotifyOperatorTempCmd;

/* const part of ActorClass (ROM) */
typedef struct NotifyOperatorTempCmd_const {
	#ifdef ET_MSC_LOGGER_ACTIVATE
		const char* instName;
	#endif
	
	/* simple ports */
	const tempLvlInfoPort receiveTempLevel;

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} NotifyOperatorTempCmd_const;


/* constant for state machine data */
#define NOTIFYOPERATORTEMPCMD_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct NotifyOperatorTempCmd {
	const NotifyOperatorTempCmd_const* ET_CONST_MEMBER constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/
	 int32 criticalCnt;
	 int32 threshold;
	 uint32 LED_PIN;
	 float32 tempTreshold;
	 bool okreported;
	 bool criticalReportedTmp;


	/* state machine variables */
	etInt16 state;
	etInt16 history[NOTIFYOPERATORTEMPCMD_HISTORY_SIZE];
};

void NotifyOperatorTempCmd_init(NotifyOperatorTempCmd* self);

void NotifyOperatorTempCmd_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_NOTIFYOPERATORTEMPCMD_H_ */

