/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass sendInfoCriticalFL
 * 
 */

#ifndef _TEMPLATEMODEL_SENDINFOCRITICALFL_UTILS_H_
#define _TEMPLATEMODEL_SENDINFOCRITICALFL_UTILS_H_

#include "TemplateModel/sendInfoCriticalFL.h"

/*
 * access macros for operations and attributes
*/


#endif /* _TEMPLATEMODEL_SENDINFOCRITICALFL_UTILS_H_ */

