/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass tempLvlInfo
 * 
 */

#ifndef _TEMPLATEMODEL_TEMPLVLINFO_UTILS_H_
#define _TEMPLATEMODEL_TEMPLVLINFO_UTILS_H_

#include "TemplateModel/tempLvlInfo.h"

/*
 * access macros for operations and attributes
*/


#endif /* _TEMPLATEMODEL_TEMPLVLINFO_UTILS_H_ */

