/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass tempLvlInfo
 * 
 */

#include "tempLvlInfo.h"
#include "debugging/etMSCLogger.h"
#include "tempLvlInfo_Utils.h"


/*--------------------- port methods */
etInt32 tempLvlInfoReplPort_getReplication(const tempLvlInfoReplPort* self) {
	return ((etReplPort*)self)->size;
}



void tempLvlInfoConjPort_value(const tempLvlInfoConjPort* self, int32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("tempLvlInfoConjPort", "value")
		etPort_sendMessage(self, tempLvlInfo_IN_value, sizeof(int32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "value", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void tempLvlInfoConjReplPort_value_broadcast(const tempLvlInfoConjReplPort* self, int32 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("tempLvlInfoConjReplPort", "value")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), tempLvlInfo_IN_value, sizeof(int32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "value", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void tempLvlInfoConjReplPort_value(const tempLvlInfoConjReplPort* self, int idx__et, int32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("tempLvlInfoConjReplPort", "value")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), tempLvlInfo_IN_value, sizeof(int32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "value", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 tempLvlInfoConjReplPort_getReplication(const tempLvlInfoConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



/*--------------------- debug helpers */
#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	
	/* message names as strings for debugging (generate MSC) */
	static const char* const tempLvlInfo_messageStrings[] = {"MIN", "value", "MAX"};
	
	const char* tempLvlInfo_getMessageString(int msg_id) {
		if (msg_id<tempLvlInfo_MSG_MIN || msg_id>tempLvlInfo_MSG_MAX+1){
			/* id out of range */
			return "Message ID out of range";
		}
		else{
			return tempLvlInfo_messageStrings[msg_id];
		}
	}
#endif
