/**
 * @author generated by eTrice
 *
 * Header File of ActorClass TopActor
 *
 */

#ifndef _TEMPLATEMODEL_TOPACTOR_H_
#define _TEMPLATEMODEL_TOPACTOR_H_

#include "modelbase/etActor.h"

/* include all referenced room classes */
#include "TemplateModel/fire.h"
#include "TemplateModel/flLvlInfo.h"
#include "TemplateModel/sendInfoCriticalFL.h"
#include "TemplateModel/tempLvlInfo.h"
#include "TemplateModel/uwbInfo.h"
#include "etrice/api/timer/PTimer.h"


typedef struct TopActor TopActor;

/* const part of ActorClass (ROM) */
typedef struct TopActor_const {
	#ifdef ET_MSC_LOGGER_ACTIVATE
		const char* instName;
	#endif
	#if !defined(ET_MSC_LOGGER_ACTIVATE) 
		/* This actor class has no const data. To keep this case simple we introduce this dummy variable. */
		int dummy;
	#endif
	
	/* simple ports */

	/* data receive ports */

	/* saps */

	/* replicated ports */

	/* services */
} TopActor_const;


/* variable part of ActorClass (RAM) */
struct TopActor {
	const TopActor_const* ET_CONST_MEMBER constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/

};

void TopActor_init(TopActor* self);

void TopActor_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_TOPACTOR_H_ */

