/**
 * @author generated by eTrice
 *
 * Source File of ActorClass TopActor
 *
 */

#include "TopActor.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"
#ifdef ET_MSC_TRACER_ACTIVATE
	#include "debugging/etMSCTracer.h"
#endif

#include "TemplateModel/fire.h"
#include "TemplateModel/flLvlInfo.h"
#include "TemplateModel/sendInfoCriticalFL.h"
#include "TemplateModel/tempLvlInfo.h"
#include "TemplateModel/uwbInfo.h"
#include "etrice/api/timer/PTimer.h"

#include "TopActor_Utils.h"


/* interface item IDs */
/* empty enum not generated */


void TopActor_init(TopActor* self){
	ET_MSC_LOGGER_SYNC_ENTRY("TopActor", "init")
	ET_MSC_LOGGER_SYNC_EXIT
}


void TopActor_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("TopActor", "_receiveMessage")

	ET_MSC_LOGGER_SYNC_EXIT
}


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/

