/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass uwbInfo
 * 
 */

#include "uwbInfo.h"
#include "debugging/etMSCLogger.h"
#include "uwbInfo_Utils.h"


/*--------------------- port methods */
etInt32 uwbInfoReplPort_getReplication(const uwbInfoReplPort* self) {
	return ((etReplPort*)self)->size;
}



void uwbInfoConjPort_value(const uwbInfoConjPort* self, float32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("uwbInfoConjPort", "value")
		etPort_sendMessage(self, uwbInfo_IN_value, sizeof(float32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(self->myInstName, "value", self->peerInstName)
	ET_MSC_LOGGER_SYNC_EXIT
}

void uwbInfoConjReplPort_value_broadcast(const uwbInfoConjReplPort* self, float32 data__et) {
	int i;
	ET_MSC_LOGGER_SYNC_ENTRY("uwbInfoConjReplPort", "value")
	for (i=0; i<((etReplPort*)self)->size; ++i) {
		etPort_sendMessage((&((etReplPort*)self)->ports[i].port), uwbInfo_IN_value, sizeof(float32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[i].port.myInstName, "value", ((etReplPort*)self)->ports[i].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

void uwbInfoConjReplPort_value(const uwbInfoConjReplPort* self, int idx__et, float32 data__et) {
	ET_MSC_LOGGER_SYNC_ENTRY("uwbInfoConjReplPort", "value")
	if (0<=idx__et && idx__et<((etReplPort*)self)->size) {
		etPort_sendMessage((&((etReplPort*)self)->ports[idx__et].port), uwbInfo_IN_value, sizeof(float32), &data__et);
		ET_MSC_LOGGER_ASYNC_OUT(((etReplPort*)self)->ports[idx__et].port.myInstName, "value", ((etReplPort*)self)->ports[idx__et].port.peerInstName)
	}
	ET_MSC_LOGGER_SYNC_EXIT
}

etInt32 uwbInfoConjReplPort_getReplication(const uwbInfoConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



/*--------------------- debug helpers */
#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	
	/* message names as strings for debugging (generate MSC) */
	static const char* const uwbInfo_messageStrings[] = {"MIN", "value", "MAX"};
	
	const char* uwbInfo_getMessageString(int msg_id) {
		if (msg_id<uwbInfo_MSG_MIN || msg_id>uwbInfo_MSG_MAX+1){
			/* id out of range */
			return "Message ID out of range";
		}
		else{
			return uwbInfo_messageStrings[msg_id];
		}
	}
#endif
