/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass uwbInfo
 * 
 */

#ifndef _TEMPLATEMODEL_UWBINFO_UTILS_H_
#define _TEMPLATEMODEL_UWBINFO_UTILS_H_

#include "TemplateModel/uwbInfo.h"

/*
 * access macros for operations and attributes
*/


#endif /* _TEMPLATEMODEL_UWBINFO_UTILS_H_ */

