/**
 * @author generated by eTrice
 *
 * Header File of ActorClass UwbSensorMissileData
 *
 */

#ifndef _TEMPLATEMODEL_UWBSENSORMISSILEDATA_H_
#define _TEMPLATEMODEL_UWBSENSORMISSILEDATA_H_

#include "modelbase/etActor.h"

/* include all referenced room classes */
#include "TemplateModel/uwbInfo.h"
#include "etrice/api/timer/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "FreeRTOS.h"
						#include "task.h"
						#include <stdio.h>
						#include "pico/stdlib.h"
						#include <queue.h>
						#include "hardware/adc.h"
						#include "hardware/watchdog.h"
						#include "semphr.h"
						#include "hardware/i2c.h"
						#include "pico/binary_info.h"
						#include "lcd.h"
						
						#include <ctype.h>
						#include "ultrsonic.h"
						#include <string.h>
						

/*--------------------- end user code ---------------------*/

typedef struct UwbSensorMissileData UwbSensorMissileData;

/* const part of ActorClass (ROM) */
typedef struct UwbSensorMissileData_const {
	#ifdef ET_MSC_LOGGER_ACTIVATE
		const char* instName;
	#endif
	
	/* simple ports */
	const uwbInfoConjPort sendDistance;

	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;

	/* replicated ports */

	/* services */
} UwbSensorMissileData_const;


/* constant for state machine data */
#define UWBSENSORMISSILEDATA_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct UwbSensorMissileData {
	const UwbSensorMissileData_const* ET_CONST_MEMBER constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[UWBSENSORMISSILEDATA_HISTORY_SIZE];
};

void UwbSensorMissileData_init(UwbSensorMissileData* self);

void UwbSensorMissileData_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_UWBSENSORMISSILEDATA_H_ */

