/**
 * @author generated by eTrice
 *
 * Header File of ActorClass WaterLevelActor
 *
 */

#ifndef _TEMPLATEMODEL_WATERLEVELACTOR_H_
#define _TEMPLATEMODEL_WATERLEVELACTOR_H_

#include "modelbase/etActor.h"

/* include all referenced room classes */
#include "TemplateModel/flLvlInfo.h"
#include "etrice/api/timer/PTimer.h"

/*--------------------- begin user code ---------------------*/
#include "FreeRTOS.h"
						#include "task.h"
						#include <stdio.h>
						#include "pico/stdlib.h"
						#include <queue.h>
						#include "hardware/adc.h"
						#include "hardware/watchdog.h"
						#include "semphr.h"
						#include "hardware/i2c.h"
						#include "pico/binary_info.h"
						#include "lcd.h"
						#include "semaphore.h"
						#include <ctype.h>
						#include "ultrsonic.h"
						#include <string.h>
						

/*--------------------- end user code ---------------------*/

typedef struct WaterLevelActor WaterLevelActor;

/* const part of ActorClass (ROM) */
typedef struct WaterLevelActor_const {
	#ifdef ET_MSC_LOGGER_ACTIVATE
		const char* instName;
	#endif
	
	/* simple ports */
	const flLvlInfoConjPort sendFluelLevel;

	/* data receive ports */

	/* saps */
	const PTimerConjPort timer;

	/* replicated ports */

	/* services */
} WaterLevelActor_const;


/* constant for state machine data */
#define WATERLEVELACTOR_HISTORY_SIZE 2

/* variable part of ActorClass (RAM) */
struct WaterLevelActor {
	const WaterLevelActor_const* ET_CONST_MEMBER constData;

	/* data send ports */

	/*--------------------- attributes ---------------------*/


	/* state machine variables */
	etInt16 state;
	etInt16 history[WATERLEVELACTOR_HISTORY_SIZE];
};

void WaterLevelActor_init(WaterLevelActor* self);

void WaterLevelActor_receiveMessage(void* self, const void* ifitem, const etMessage* msg);


/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/


#endif /* _TEMPLATEMODEL_WATERLEVELACTOR_H_ */

