/**
 * @author generated by eTrice
 *
 * Source File of ActorClass ATimerService
 *
 */

#include "ATimerService.h"

#include "debugging/etLogger.h"
#include "debugging/etMSCLogger.h"
#include "etUnit/etUnit.h"
#include "base/etMemory.h"
#ifdef ET_MSC_TRACER_ACTIVATE
	#include "debugging/etMSCTracer.h"
#endif

#include "etrice/api/timer/PTimer.h"
#include "etrice/api/timer/PTimerSupervisionControl.h"

#include "ATimerService_Utils.h"


/* interface item IDs */
enum interface_items {
	IFITEM_timer = 1,
	IFITEM_supervisionControl = 2
};

/* state IDs */
enum state_ids {
	NO_STATE = 0,
	STATE_TOP = 1,
	STATE_Operational = 2,
	STATE_MAX = 3
};

/* transition chains */
enum ChainIDs {
	CHAIN_TRANS_INITIAL_TO__Operational = 1,
	CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY__startTimeouttimer_tr1 = 2,
	CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY__startTimertimer_tr3 = 3,
	CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4 = 4,
	CHAIN_TRANS_tr2_FROM_Operational_TO_Operational_BY_getTimerDeviationHighWaterMarksupervisionControl_tr2 = 5,
	CHAIN_TRANS_tr5_FROM_Operational_TO_Operational_BY_restTimerDeviationHighWaterMarksupervisionControl_tr5 = 6
};

/* triggers */
enum triggers {
	POLLING = 0,
	TRIG_timer__startTimer = IFITEM_timer + EVT_SHIFT*PTimer_IN_startTimer,
	TRIG_timer__startTimeout = IFITEM_timer + EVT_SHIFT*PTimer_IN_startTimeout,
	TRIG_timer__kill = IFITEM_timer + EVT_SHIFT*PTimer_IN_kill,
	TRIG_timer___startTimer = IFITEM_timer + EVT_SHIFT*PTimer_IN__startTimer,
	TRIG_timer___startTimeout = IFITEM_timer + EVT_SHIFT*PTimer_IN__startTimeout,
	TRIG_supervisionControl__restTimerDeviationHighWaterMark = IFITEM_supervisionControl + EVT_SHIFT*PTimerSupervisionControl_IN_restTimerDeviationHighWaterMark,
	TRIG_supervisionControl__getTimerDeviationHighWaterMark = IFITEM_supervisionControl + EVT_SHIFT*PTimerSupervisionControl_IN_getTimerDeviationHighWaterMark
};

/* state names */
#ifdef ET_MSC_LOGGER_ACTIVATE
	static const char* stateStrings[] = {"<no state>","<top>","Operational"
	};
#endif

static void setState(ATimerService* self, etInt16 new_state) {
	self->state = new_state;
	ET_MSC_LOGGER_CHANGE_STATE(self->constData->instName, stateStrings[new_state]);
}

static etInt16 getState(ATimerService* self) {
	return self->state;
}

/* Entry and Exit Codes */
static  void do_Operational(ATimerService* self) {
	/* maintain timers */
	etTimerControlBlock *temp;
	etTime t;
	
	getTime(&t);
	while (usedTcbsRoot != 0) {
		if (etTimeHelpers_isGreater(&t, &(usedTcbsRoot->expTime))) {
			// maintain deviation hig water mark
			etTime delta = t;
			etTimeHelpers_subtract(&delta, &(usedTcbsRoot->expTime));
			if (etTimeHelpers_isGreater(&delta, &timerDeviationHighWaterMark)) {
				timerDeviationHighWaterMark = delta;
			}
			timer__timeout(usedTcbsRoot->portIdx, usedTcbsRoot->timeId);
			temp = usedTcbsRoot;
			usedTcbsRoot = usedTcbsRoot->next;
			if ((temp->pTime.sec == 0) && (temp->pTime.nSec == 0)) {
				/* single shot timer */
			} else {
				/* periodic timer */
				etTimeHelpers_add(&temp->expTime, &temp->pTime);
				// if new expiry time is before current time, recover and notify
				if (etTimeHelpers_isGreater(&t, &(temp->expTime))) {
					temp->expTime = t;
					etTimeHelpers_add(&(temp->expTime), &(temp->pTime));
					etLogger_logError("ATimerService: late periodic timeout dropped and rescheduled!");
				}
				putTcbToUsedList(temp);
			}
		} else {
			break;
		}
	}
}

/* Action Codes */
static void action_TRANS_INITIAL_TO__Operational(ATimerService* self) {
	usedTcbsRoot=0;
	timerDeviationHighWaterMark.sec = 0;
	timerDeviationHighWaterMark.nSec = 0;
}
static void action_TRANS_tr1_FROM_Operational_TO_Operational_BY__startTimeouttimer_tr1(ATimerService* self, const InterfaceItemBase* ifitem, DStartTimer* transitionData) {
	queueTcb((void*) ifitem, transitionData, false);
}
static void action_TRANS_tr3_FROM_Operational_TO_Operational_BY__startTimertimer_tr3(ATimerService* self, const InterfaceItemBase* ifitem, DStartTimer* transitionData) {
	queueTcb((void*) ifitem, transitionData, true);
}
static void action_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4(ATimerService* self, const InterfaceItemBase* ifitem) {
	removeTcbFromUsedList(((etReplSubPort*)ifitem)->index);
}
static void action_TRANS_tr2_FROM_Operational_TO_Operational_BY_getTimerDeviationHighWaterMarksupervisionControl_tr2(ATimerService* self, const InterfaceItemBase* ifitem) {
	uint32 dt;
	
	dt = timerDeviationHighWaterMark.nSec / 1000 + timerDeviationHighWaterMark.sec * 1000000;
	supervisionControl_timerDeviationHighWaterMark(((etReplSubPort*)ifitem)->index, dt);
}
static void action_TRANS_tr5_FROM_Operational_TO_Operational_BY_restTimerDeviationHighWaterMarksupervisionControl_tr5(ATimerService* self, const InterfaceItemBase* ifitem) {
	ET_TOUCH(ifitem);
	timerDeviationHighWaterMark.sec = 0;
	timerDeviationHighWaterMark.nSec = 0;
}

/* State Switch Methods */
/**
 * calls exit codes while exiting from the current state to one of its
 * parent states while remembering the history
 * @param current__et - the current state
 * @param to - the final parent state
 */
static void exitTo(ATimerService* self, etInt16 current__et, etInt16 to) {
	while (current__et!=to) {
		switch (current__et) {
			case STATE_Operational:
				self->history[STATE_TOP] = STATE_Operational;
				current__et = STATE_TOP;
				break;
			default:
				/* should not occur */
				break;
		}
	}
}

/**
 * calls action, entry and exit codes along a transition chain. The generic data are cast to typed data
 * matching the trigger of this chain. The ID of the final state is returned
 * @param chain__et - the chain ID
 * @param generic_data__et - the generic data pointer
 * @return the +/- ID of the final state either with a positive sign, that indicates to execute the state's entry code, or a negative sign vice versa
 */
static etInt16 executeTransitionChain(ATimerService* self, int chain__et, const InterfaceItemBase* ifitem, void* generic_data__et) {
	switch (chain__et) {
		case CHAIN_TRANS_INITIAL_TO__Operational:
		{
			action_TRANS_INITIAL_TO__Operational(self);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY__startTimeouttimer_tr1:
		{
			DStartTimer* transitionData = ((DStartTimer*) generic_data__et);
			ET_TOUCH(transitionData);
			action_TRANS_tr1_FROM_Operational_TO_Operational_BY__startTimeouttimer_tr1(self, ifitem, transitionData);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr2_FROM_Operational_TO_Operational_BY_getTimerDeviationHighWaterMarksupervisionControl_tr2:
		{
			action_TRANS_tr2_FROM_Operational_TO_Operational_BY_getTimerDeviationHighWaterMarksupervisionControl_tr2(self, ifitem);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY__startTimertimer_tr3:
		{
			DStartTimer* transitionData = ((DStartTimer*) generic_data__et);
			ET_TOUCH(transitionData);
			action_TRANS_tr3_FROM_Operational_TO_Operational_BY__startTimertimer_tr3(self, ifitem, transitionData);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4:
		{
			action_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4(self, ifitem);
			return STATE_Operational;
		}
		case CHAIN_TRANS_tr5_FROM_Operational_TO_Operational_BY_restTimerDeviationHighWaterMarksupervisionControl_tr5:
		{
			action_TRANS_tr5_FROM_Operational_TO_Operational_BY_restTimerDeviationHighWaterMarksupervisionControl_tr5(self, ifitem);
			return STATE_Operational;
		}
			default:
				/* should not occur */
				break;
	}
	return NO_STATE;
}

/**
 * calls entry codes while entering a state's history. The ID of the final leaf state is returned
 * @param state__et - the state which is entered
 * @return - the ID of the final leaf state
 */
static etInt16 enterHistory(ATimerService* self, etInt16 state__et) {
	if (state__et >= STATE_MAX) {
		state__et = (etInt16) (state__et - STATE_MAX);
	}
	while (ET_TRUE) {
		switch (state__et) {
			case STATE_Operational:
				/* in leaf state: return state id */
				return STATE_Operational;
			case STATE_TOP:
				state__et = self->history[STATE_TOP];
				break;
			default:
				/* should not occur */
				break;
		}
	}
	/* return NO_STATE; // required by CDT but detected as unreachable by JDT because of while (true) */
}

static void ATimerService_executeInitTransition(ATimerService* self) {
	int chain__et = CHAIN_TRANS_INITIAL_TO__Operational;
	etInt16 next__et = executeTransitionChain(self, chain__et, NULL, NULL);
	next__et = enterHistory(self, next__et);
	setState(self, next__et);
}

/* receiveEvent contains the main implementation of the FSM */
static void ATimerService_receiveEventInternal(ATimerService* self, InterfaceItemBase* ifitem, int localId, int evt, void* generic_data__et) {
	int trigger__et = (ifitem==NULL)? POLLING : localId + EVT_SHIFT*evt;
	int chain__et = NOT_CAUGHT;
	etInt16 catching_state__et = NO_STATE;
	((void)trigger__et);	/* avoids unused warning */

	if (!handleSystemEvent(ifitem, evt, generic_data__et)) {
		switch (getState(self)) {
			case STATE_Operational:
				switch(trigger__et) {
					case POLLING:
						do_Operational(self);
						break;
					case TRIG_supervisionControl__getTimerDeviationHighWaterMark:
						{
							chain__et = CHAIN_TRANS_tr2_FROM_Operational_TO_Operational_BY_getTimerDeviationHighWaterMarksupervisionControl_tr2;
							catching_state__et = STATE_TOP;
						}
					break;
					case TRIG_supervisionControl__restTimerDeviationHighWaterMark:
						{
							chain__et = CHAIN_TRANS_tr5_FROM_Operational_TO_Operational_BY_restTimerDeviationHighWaterMarksupervisionControl_tr5;
							catching_state__et = STATE_TOP;
						}
					break;
					case TRIG_timer___startTimeout:
						{
							chain__et = CHAIN_TRANS_tr1_FROM_Operational_TO_Operational_BY__startTimeouttimer_tr1;
							catching_state__et = STATE_TOP;
						}
					break;
					case TRIG_timer___startTimer:
						{
							chain__et = CHAIN_TRANS_tr3_FROM_Operational_TO_Operational_BY__startTimertimer_tr3;
							catching_state__et = STATE_TOP;
						}
					break;
					case TRIG_timer__kill:
						{
							chain__et = CHAIN_TRANS_tr4_FROM_Operational_TO_Operational_BY_killtimer_tr4;
							catching_state__et = STATE_TOP;
						}
					break;
					default:
						/* should not occur */
						break;
				}
				break;
			default:
				/* should not occur */
				break;
		}
	}
	if (chain__et != NOT_CAUGHT) {
		exitTo(self, getState(self), catching_state__et);
		{
			etInt16 next__et = executeTransitionChain(self, chain__et, ifitem, generic_data__et);
			next__et = enterHistory(self, next__et);
			setState(self, next__et);
		}
	}
}
static void ATimerService_receiveEvent(ATimerService* self, InterfaceItemBase* ifitem, int evt, void* generic_data__et) {
	int localId = (ifitem==NULL)? 0 : ifitem->localId;
	ATimerService_receiveEventInternal(self, ifitem, localId, evt, generic_data__et);
}

void ATimerService_init(ATimerService* self){
	ET_MSC_LOGGER_SYNC_ENTRY("ATimerService", "init")
	self->state = STATE_TOP;
	{
		int i;
		for (i=0; i<ATIMERSERVICE_HISTORY_SIZE; ++i)
			self->history[i] = NO_STATE;
	}
	ATimerService_executeInitTransition(self);
	ET_MSC_LOGGER_SYNC_EXIT
}


void ATimerService_receiveMessage(void* self, const void* ifitem, const etMessage* msg){
	ET_MSC_LOGGER_SYNC_ENTRY("ATimerService", "_receiveMessage")
	ATimerService_receiveEvent((ATimerService*) self, (etPort*)ifitem, msg->evtID, (void*)(((char*)msg)+MEM_CEIL(sizeof(etMessage))));

	ET_MSC_LOGGER_SYNC_EXIT
}

void ATimerService_execute(ATimerService* self) {
	ET_MSC_LOGGER_SYNC_ENTRY("ATimerService", "_execute")

	ATimerService_receiveEvent(self, NULL, 0, NULL);

	ET_MSC_LOGGER_SYNC_EXIT
}

/*--------------------- user constructor/destructor ---------------------*/

/*--------------------- operations ---------------------*/
 void ATimerService_putTcbToUsedList(ATimerService* self, etTimerControlBlock* block) {
	etTimerControlBlock *temp = usedTcbsRoot;
	etTimerControlBlock *temp2 = usedTcbsRoot;
	
	if (temp == 0) {
		/* list empty put new block to root */
		block->next = 0;
		usedTcbsRoot = block;
		return;
	}
	
	while (1) {
		if (temp != 0) {
			if (etTimeHelpers_isGreater(&block->expTime, &temp->expTime)) {
				/* try next position */
				temp2 = temp;
				temp = temp->next;
			} else {
				/* right position found */
				block->next = temp;
				if (temp == usedTcbsRoot) {
					usedTcbsRoot = block;
				} else {
					temp2->next = block;
				}
				return;
			}
		} else {
			/* end of list reached */
			block->next = 0;
			temp2->next = block;
			return;
		}
	}
}
 void ATimerService_queueTcb(ATimerService* self, void* ifitem, DStartTimer* startTimer, bool periodic) {
	// The portclass blocks repeated start messages if a timer is running
	etAddressId portIdx = ((etReplSubPort*) ifitem)->index;
	PTimerPort_var *portClassVarData = (PTimerPort_var*) (self->constData->timer.ports[portIdx].port.varData);
	etTimerControlBlock *tcb = &(portClassVarData->tcb);
	etTime t;
	if (tcb != 0) {
		t.sec = (etInt32) (startTimer->timeMs / 1000U);
		t.nSec = (etInt32) ((startTimer->timeMs % 1000U) * 1000000U);
		if (periodic) {
			tcb->pTime = t;
		} else {
			tcb->pTime.sec = 0;
			tcb->pTime.nSec = 0;
		}
		tcb->portIdx = ((etReplSubPort*) ifitem)->index;
		tcb->timeId = startTimer->timeId;
		getTime(&(tcb->expTime));
		etTimeHelpers_add(&(tcb->expTime), &t);
		putTcbToUsedList(tcb);
	} else {
		etLogger_logError("ATimerService: no timer available!");
	}
}
 void ATimerService_getTime(ATimerService* self, etTime* t) {
	ET_TOUCH(self);
	getTimeFromTarget(t);
}
 void ATimerService_removeTcbFromUsedList(ATimerService* self, int32 idx) {
	etTimerControlBlock *temp = usedTcbsRoot;
	etTimerControlBlock *temp2 = usedTcbsRoot;
	
	if (temp == 0)
		return;
	
	if (usedTcbsRoot->portIdx == idx) {
		/* element found, the first one */
		usedTcbsRoot = usedTcbsRoot->next;
		return;
	}
	
	temp = temp->next;
	while (temp != 0) {
		if (temp->portIdx == idx) {
			temp2->next = temp->next;
			return;
		} else {
			/* try next */
			temp2 = temp;
			temp = temp->next;
		}
	}
}

