/**
 * @author generated by eTrice
 *
 * Header File of DataClass DStartTimer
 * 
 */

#ifndef _ETRICE_API_TIMER_DSTARTTIMER_H_
#define _ETRICE_API_TIMER_DSTARTTIMER_H_

#include "etDatatypes.h"

/* include all referenced room classes */

		
typedef struct {
	/*--------------------- attributes ---------------------*/
	 uint32 timeMs;
	 uint16 timeId;
} DStartTimer;



/*--------------------- operations ---------------------*/

/* deep copy */
void DStartTimer_deepCopy(DStartTimer* source, DStartTimer* target);


#endif /* _ETRICE_API_TIMER_DSTARTTIMER_H_ */

