/**
 * @author generated by eTrice
 *
 * Source File of DataClass DStartTimer
 * 
 */

#include <string.h>

#include "DStartTimer.h"
#include "DStartTimer_Utils.h"



/*--------------------- operations ---------------------*/

void DStartTimer_deepCopy(DStartTimer* source, DStartTimer* target) {
	memcpy(target, source, sizeof(DStartTimer));
}

