/**
 * @author generated by eTrice
 *
 * Utils File of DataClass DStartTimer
 * 
 */

#ifndef _ETRICE_API_TIMER_DSTARTTIMER_UTILS_H_
#define _ETRICE_API_TIMER_DSTARTTIMER_UTILS_H_

#include "etrice/api/timer/DStartTimer.h"

/*
 * access macros for operations and attributes
*/

/* operations */

/* attributes */
#define timeMs (self->timeMs)
#define timeId (self->timeId)

#endif /* _ETRICE_API_TIMER_DSTARTTIMER_UTILS_H_ */

