/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PTimer
 * 
 */

#ifndef _ETRICE_API_TIMER_PTIMER_UTILS_H_
#define _ETRICE_API_TIMER_PTIMER_UTILS_H_

#include "etrice/api/timer/PTimer.h"

/*
 * access macros for operations and attributes
*/

/* regular port class */

/* operations */

/* attributes */
#define tcb (((PTimerPort_var*)(self->varData))->tcb)
/* conjugate port class */

/* operations */

/* attributes */
#define status (((PTimerConjPort_var*)(self->varData))->status)
#define currentTimeId (((PTimerConjPort_var*)(self->varData))->currentTimeId)

#endif /* _ETRICE_API_TIMER_PTIMER_UTILS_H_ */

