/**
 * @author generated by eTrice
 *
 * Utils File of ProtocolClass PLoggerFlush
 * 
 */

#ifndef _ETRICE_API_LOGGER_PLOGGERFLUSH_UTILS_H_
#define _ETRICE_API_LOGGER_PLOGGERFLUSH_UTILS_H_

#include "etrice/api/logger/PLoggerFlush.h"

/*
 * access macros for operations and attributes
*/


#endif /* _ETRICE_API_LOGGER_PLOGGERFLUSH_UTILS_H_ */

