/**
 * @author generated by eTrice
 *
 * Source File of ProtocolClass PLogger
 * 
 */

#include "PLogger.h"
#include "debugging/etMSCLogger.h"
#include "PLogger_Utils.h"


/*--------------------- port methods */
etInt32 PLoggerReplPort_getReplication(const PLoggerReplPort* self) {
	return ((etReplPort*)self)->size;
}


/* begin PLoggerConjPort specific (including base classes) */

/*--------------------- operations ---------------------*/
 void PLoggerConjPort_log(PLoggerConjPort* self, char* message) {
	// TODO call etLogger
}
 void PLoggerConjPort_logF(PLoggerConjPort* self, char* format, ...) {
	// TODO call etLogger
}
/* end PLoggerConjPort specific (including base classes) */

etInt32 PLoggerConjReplPort_getReplication(const PLoggerConjReplPort* self) {
	return ((etReplPort*)self)->size;
}



/*--------------------- debug helpers */
#ifdef ET_ASYNC_MSC_LOGGER_ACTIVATE
	
	/* message names as strings for debugging (generate MSC) */
	static const char* const PLogger_messageStrings[] = {"MIN", "MAX"};
	
	const char* PLogger_getMessageString(int msg_id) {
		if (msg_id<PLogger_MSG_MIN || msg_id>PLogger_MSG_MAX+1){
			/* id out of range */
			return "Message ID out of range";
		}
		else{
			return PLogger_messageStrings[msg_id];
		}
	}
#endif
